# Generated by Django 3.2.7 on 2021-12-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_make_follow_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
