# Generated by Django 3.2.7 on 2021-12-25 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow_to',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follow_from',
            new_name='following',
        ),
    ]
